import { Logger } from "pino";
import { MarkdownMetadata } from "../content";
import { index } from '../../server/src/bootstrap';

/**
 * Small Index: Suitable for browser search
 * Large Index: Suitable for server search, more memory usage, for better full-text search e.g. Thai language
 */
export type IndexSize = 'small' | 'large';

export interface ExecuteBuildSearchIndexOptions {
  cwd?: string;
  postMetadataFile: string;
  searchIndexPath: string;
  /**
   * Search index SiteMap path, for loading search index in browser
   */
  searchIndexMetadataPath: string;
  /**
   * Root public directory
   */
  rootPublicDir: string;
  /**
   * Index Size
   */
  indexSize: IndexSize;
}

export interface BuildSearchIndexOptions {
  markdownData: MarkdownMetadata[];
  logger?: Logger;
  indexSize: IndexSize;
}

export interface ImportSearchIndexOptions {
  searchIndexPath: string;
  logger?: Logger;
  indexSize: IndexSize;
}

export interface ImportSearchIndexFromRemoteOptions {
  /**
   * Search index metadata path e.g. /api/search-index-metadata.json
   * Typically, this file is generated by `executeBuildSearchIndex`
   * 
   * The index size depends on given metadata path
   */
  searchIndexMetadataPath: string;
  /**
   * Index Size
   */
  indexSize: IndexSize;
  logger?: Logger;
}

export interface SearchIndexMetadataResponse {
  /**
   * Location of search index files
   */
  sitemap: string[];
}