name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

env:
  SWA_ENVIRONMENT: "production"
  SWA_NAME: "thadaw-main-site-v8"
  # Version of Zola available in GitHub releases.
  # Ref: https://www.getzola.org/documentation/deployment/gitlab-pages/
  ZOLA_VERSION: "0.19.2"

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: oven-sh/setup-bun@v2

      - name: Install Scripts Dependencies
        run: bun install
        working-directory: scripts

      - name: Install Zola
        run: |
          zola_url="https://github.com/getzola/zola/releases/download/v$ZOLA_VERSION/zola-v$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz"
          if ! wget --quiet --spider $zola_url; then
            echo "A Zola release with the specified version could not be found.";
            exit 1;
          fi
          wget $zola_url
          tar -xzf *.tar.gz

      - name: Build
        run: |
          ./zola build
          make id-mapper
          make clean-js-build

      - name: Deploy
        run: bunx @azure/static-web-apps-cli deploy ./public --env ${{ env.SWA_ENVIRONMENT}} -n  ${{ env.SWA_NAME }}
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_PEBBLE_0100C4100 }}
